spring:
  application:
    name: mini-social-network
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/socialnetwork
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    jpa:
      hibernate:
        ddl-auto: update
    hikari:
      auto-commit: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB


jwt:
  secret: "Q2F0aGVkcmtmdWRvb2Rrc2QxMjNqZmhsbGthc2tsamZrbGZhc2tmYWxsa2Fqc2Y="
  expiration: 3600000 # 1 hour in milliseconds

server:
  port: 8080


